# Generated by Django 5.1.7 on 2025-04-01 22:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Property Name"),
                ),
                (
                    "street_address",
                    models.CharField(max_length=255, verbose_name="Street Address"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state", models.CharField(max_length=50, verbose_name="State")),
                ("zip_code", models.CharField(max_length=20, verbose_name="Zip Code")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "owners",
                    models.TextField(
                        blank=True,
                        help_text="Names or details of owners",
                        null=True,
                        verbose_name="Owner(s)",
                    ),
                ),
                (
                    "property_manager",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Property Manager",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Target",
                "verbose_name_plural": "Targets",
                "ordering": ["name"],
            },
        ),
    ]
