# Generated by Django 5.1.7 on 2025-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Street Address"
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Zip Code"
            ),
        ),
    ]
