version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-secret_shop_dev}
      - POSTGRES_USER=${DB_USER:-secret_shop_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-dev_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-secret_shop_user} -d ${DB_NAME:-secret_shop_dev}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: secret_shop_postgres_data
