# Generated by Django 5.1.7 on 2025-04-01 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personas", "0001_initial"),
        ("targets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="The current status of the shop.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="The persona used for this shop.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shops",
                        to="personas.persona",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="The target being shopped.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="targets.target",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who initiated the shop.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShopResult",
            fields=[
                (
                    "shop",
                    models.OneToOneField(
                        help_text="The shop this result belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="result",
                        serialize=False,
                        to="shops.shop",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of the interaction."
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data extracted from the interaction.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shop Result",
                "verbose_name_plural": "Shop Results",
            },
        ),
    ]
