# Generated by Django 5.1.7 on 2025-04-09 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0001_initial"),
        ("shops", "0002_amenity_alter_shopresult_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                help_text="The persona used for this shop.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shops",
                to="personas.persona",
            ),
        ),
    ]
