# Generated by Django 5.1.7 on 2025-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_alter_shop_persona"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When the shop process was completed or failed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="start_time",
            field=models.DateTimeField(
                blank=True, help_text="When the shop process was started.", null=True
            ),
        ),
    ]
