# Generated by Django 5.1.7 on 2025-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_shop_end_time_shop_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityinfo",
            name="membership_fee",
            field=models.CharField(
                blank=True,
                help_text="Recurring membership or resident benefit package fee.",
                max_length=500,
                null=True,
            ),
        ),
    ]
