# Generated by Django 5.1.7 on 2025-07-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_alter_communityinfo_membership_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityinfo",
            name="resident_portal_provider",
            field=models.CharField(
                blank=True,
                help_text="The software provider for the resident portal.",
                max_length=255,
                null=True,
            ),
        ),
    ]
