# Generated by Django 5.1.7 on 2025-07-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_migrate_fee_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communityinfo",
            name="administration_fee",
        ),
        migrations.RemoveField(
            model_name="communityinfo",
            name="administration_fee_source",
        ),
        migrations.RemoveField(
            model_name="communityinfo",
            name="application_fee",
        ),
        migrations.RemoveField(
            model_name="communityinfo",
            name="application_fee_source",
        ),
        migrations.RemoveField(
            model_name="communityinfo",
            name="membership_fee",
        ),
        migrations.RemoveField(
            model_name="communityinfo",
            name="membership_fee_source",
        ),
    ]
