# Generated by Django 5.1.7 on 2025-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_remove_communityinfo_administration_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="image",
            field=models.URLField(
                blank=True,
                help_text="URL to the floor plan image if available.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="num_available",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of units available for rent in this floor plan.",
                null=True,
            ),
        ),
    ]
