# Generated by Django 5.1.7 on 2025-07-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_floorplan_image_floorplan_num_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityinfo",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="The city found in community data.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communityinfo",
            name="special_offers",
            field=models.TextField(
                blank=True,
                help_text="Any special offers or promotions currently available.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communityinfo",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="The state found in community data.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communityinfo",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="The street address found in community data.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communityinfo",
            name="zip_code",
            field=models.CharField(
                blank=True,
                help_text="The zip code found in community data.",
                max_length=20,
                null=True,
            ),
        ),
    ]
