# Generated by Django 5.1.7 on 2025-04-01 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "rental_budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rental Budget"
                    ),
                ),
                (
                    "desired_bedrooms",
                    models.PositiveIntegerField(verbose_name="Desired Bedrooms"),
                ),
                (
                    "desired_bathrooms",
                    models.PositiveIntegerField(verbose_name="Desired Bathrooms"),
                ),
                (
                    "additional_preferences",
                    models.TextField(
                        blank=True, verbose_name="Additional Rental Preferences"
                    ),
                ),
                ("pets", models.TextField(blank=True, verbose_name="Pets")),
                (
                    "credit_score",
                    models.PositiveIntegerField(verbose_name="Credit Score"),
                ),
                (
                    "monthly_income",
                    models.PositiveIntegerField(verbose_name="Monthly Income"),
                ),
                (
                    "additional_occupants",
                    models.TextField(blank=True, verbose_name="Additional Occupants"),
                ),
                (
                    "rental_history",
                    models.TextField(blank=True, verbose_name="Rental History"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Template",
                "verbose_name_plural": "Persona Templates",
                "ordering": ["-created"],
            },
        ),
    ]
